### ISSUE TITLE
joplin 2.3.5 will not build because of a new python 2 dependency

### ISSUE THREAD

**Issue by taw00** [taw00/joplin-rpm#8]
As of release 2.3.3 and now 2.3.5. All builds began failing for me. :(
The first change was I had to `npm install npm` on most versions of the various OSes because they mostly all default to v6. Alas, the `filelockVersion` in `package-lock.json` changed (because the format of the file changed with v7). OK. No big deal, but I have no idea if the follow-on issue(s) is(are) related.

I get this error ... and I am unsure why except that maybe a dependency on python 2 somehow creeped back in?

```
lerna notice cli v3.22.1
lerna info versioning independent
lerna info Bootstrapping 15 packages
lerna info Installing external dependencies
lerna ERR! npm install exited 1 in '@joplin/tools'
lerna ERR! npm install stderr:
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated har-validator@5.1.3: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated node-pre-gyp@0.11.0: Please upgrade to @mapbox/node-pre-gyp: the non-scoped node-pre-gyp package is deprecated and only the @mapbox scoped package will recieve updates in the future
npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
npm ERR! code 1
npm ERR! path /builddir/build/BUILD/joplin-2.3/joplin-2.3.5/packages/tools/node_modules/sharp
npm ERR! command failed
npm ERR! command sh -c (node install/libvips && node install/dll-copy && prebuild-install --runtime=napi) || (node-gyp rebuild && node install/dll-copy)
npm ERR! info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.9.1/libvips-8.9.1-linux-x64.tar.gz
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@3.8.0
npm ERR! gyp info using node@14.17.0 | linux | x64
npm ERR! gyp ERR! configure error 
npm ERR! gyp ERR! stack Error: Command failed: /usr/bin/python3 -c import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack   File "<string>", line 1
npm ERR! gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
npm ERR! gyp ERR! stack                       ^
npm ERR! gyp ERR! stack SyntaxError: invalid syntax
npm ERR! gyp ERR! stack 
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (child_process.js:319:12)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:376:20)
npm ERR! gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
npm ERR! gyp ERR! System Linux 5.11.18-300.fc34.x86_64
npm ERR! gyp ERR! command "/usr/bin/node" "/builddir/build/BUILD/joplin-2.3/joplin-2.3.5/packages/tools/node_modules/.bin/node-gyp" "rebuild"
npm ERR! gyp ERR! cwd /builddir/build/BUILD/joplin-2.3/joplin-2.3.5/packages/tools/node_modules/sharp
npm ERR! gyp ERR! node -v v14.17.0
npm ERR! gyp ERR! node-gyp -v v3.8.0
npm ERR! gyp ERR! not ok
```

**Comment by taw00** [comment]
I was forced to build using upstream binaries which is a no-no, of course. But ... we needed a functional Joplin. I will continue to troubleshoot the issue so that we can return to normal builds from source.

**Comment by eclipseo** [comment]
https://github.com/lovell/sharp/issues/2730

Apparently you need a more recent node-gyp?

**Comment by taw00** [comment]
Well, I do a ...
```
npm install npm@latest
npm install node-gyp@latest
```
I will continue to troubleshoot.

**Comment by taw00** [comment]
Closing this. I repackage upstream binaries for the time being. Have been for a couple releases now. That may change at some future date, but for now, that is what I am doing.
